### PR TITLE
Adding TST Open Source scripts and links to data

### PR DESCRIPTION
**Pull request by Noah-Lanier**
The README.md has context for and a description of the TST dataset and the associated scripts.

feature_pipeline_tst.py creates the features.
prediction_pipeline_tst.py does prediction on those features as well as plot factors and reconstruction of features.

### CODE REVIEW

**Comment by jackgoffinet** [comment]
Hey @Noah-Lanier , I'll take a closer look at this, but for now I'm not able to download the data from the Duke Box link. I'm guessing the permissions are too restrictive. A longer term solution is to upload the data to Duke Library's repository.

Best,

Jack

**Comment by Noah-Lanier** [comment]
Sounds good @jackgoffinet. The Duke Box was a temporary solution, but I'll look into the Duke Library's repository now. I should note that I found a couple of small things I'd like to change, particularly changing groups to reflect the labels so that classes are balanced in training and testing, if I'm understanding the function of 'groups' correctly. The other changes are comment/documentation related.

**Comment by jackgoffinet** [comment]
Hi @Noah-Lanier , that sounds good.

The `groups` argument in the model methods tells the model which mouse each power volume belongs to, an array of integers with each unique integer corresponding to a mouse. The objective being optimized is a class-weighted accuracy, so it shouldn't be necessary to use the `groups` argument to try to account for label imbalance.

One thing that may be worth looking into than the simple train/test split in the example script is the `GridSearchCV` model. If you pass groups to the fit method, than a group shuffle is used to split the data into train and validation data.

Best,

Jack

**Comment by jackgoffinet** [comment]
OK -- @Noah-Lanier , I'm going to download this data and test this out sometime this week. I might move the legacy features to a separate branch because they're not really related to the TST example.

**Comment by jackgoffinet** [comment]
Hey @Noah-Lanier , I've been adding a more automated pipeline to this branch. It's in `script.py` and it reads parameters from the YAML file in the root directory. The whole pipeline can then be run with `python script.py path/to/tst_dataset`. This is close to being finished and I'll merge once it's all done.

**Comment by jackgoffinet** [comment]
@Noah-Lanier , have you made any progress on publishing the dataset?

**Comment by jackgoffinet** [comment]
I'll merge now because what's here in `script.py` is an improvement on the `feature_pipeline.py` and `prediction_pipeline.py`, but let's keep this branch alive until the TST dataset is public.

**Comment by Noah-Lanier** [comment]
> @Noah-Lanier , have you made any progress on publishing the dataset?

I've met with David about it and there are some things he has to fill out before it can be published. I'll remind him about it in our 1 on 1 meeting tomorrow. It's ready to go barring paperwork. I'll be able to check `script.py` out tomorrow, was out sick today. I'm sure it's great.

**Pull request merged**
